### PR TITLE
libckteec: Add support for CKM_AES_CMAC_GENERAL

### PR DESCRIPTION
**Pull request by vchong**
Add support for CKM_AES_CMAC* mechanisms.

Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by ruchi393** [comment]
`Acked-by: Ruchika Gupta <ruchika.gupta@linaro.org>`

**Comment by vesajaaskelainen** [comment]
Commit actually adds only support for _GENERIC as CKM_AES_CMAC was there already so commit message is a bit misleading.

`Reviewed-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>`

**Comment by vchong** [comment]
> Commit actually adds only support for _GENERIC as CKM_AES_CMAC was there already so commit message is a bit misleading.
> 
> `Reviewed-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>`

Ok. I will change commit description when adding tags. Thanks.

**Comment by vchong** [comment]
Rebased and tags added.

**Pull request merged**
