### PR TITLE
tee-supplicant: move TEEC_LOAD_PATH to Makefile

### PR DESCRIPTION
**Pull request by airbak**
TEEC_LOAD_PATH default value is "/lib", it could be changed by
CFG_TEE_CLIENT_LOAD_PATH in tee_supplicant_android.mk.
As "/lib" could not meet all the scenes, it should be able to be
changed in Makefile for Linux.

* Add -DTEEC_LOAD_PATH in Makefile
* Remove the #ifndef TEEC_LOAD_PATH block in teec_ta_load.c
* Set CFG_TEE_CLIENT_LOAD_PATH ?= /lib in config.mk
  (instead of /system/lib)
* In Android.mk, set CFG_TEE_CLIENT_LOAD_PATH ?= /system/lib
  before config.mk is included

Signed-off-by: Jianhui Li <airbak.li@hisilicon.com>

### CODE REVIEW

**Comment by vchong** [comment]
@liuyq Can you please ack for Android.mk? Thanks!

**Comment by jforissier** [comment]
For the Linux part (not Android):
```
Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>
Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMU)
```

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by liuyq** [comment]
Reviewed-by: Yongqin Liu <yongqin.liu@linaro.org>
Tested-by: Yongqin Liu <yongqin.liu@linaro.org> (Hikey with AOSP master)

**Comment by jforissier** [comment]
@airbak thanks! (and @liuyq thanks for testing on Android!)

**Pull request merged**
