### PR TITLE
aosp updates

### PR DESCRIPTION
**Pull request by vchong**

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>` for the 3 commits.

**Comment by vchong** [comment]
Tags added. Thanks.

**Comment by jforissier** [comment]
OK if this gets merged after the release?

**Comment by vchong** [comment]
> OK if this gets merged after the release?

My 3.12-rc T-b tag depended on this PR so it would be nice if this could be merged before the release. Otherwise I'll just maintain it out of tree until the next one. Thanks.

**Comment by jforissier** [comment]
> > OK if this gets merged after the release?
> 
> My 3.12-rc T-b tag depended on this PR so it would be nice if this could be merged before the release. Otherwise I'll just maintain it out of tree until the next one. Thanks.

OK, no problem.

**Pull request merged**
