### PR TITLE
travis: remove the .travis.yml file

### PR DESCRIPTION
**Pull request by jbech-linaro**
We're no longer using Travis CI and have no plans of adding it again. Hence let's remove the .travis.yml file.

### CODE REVIEW

**Review by jforissier — COMMENTED** [review]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jbech-linaro** [comment]
I've added both of your tags, ready to merge, thanks!

**Comment by jbech-linaro** [comment]
Gentle nudge @jforissier , this is ready to be merged.

**Pull request merged**
