### PR TITLE
minor aosp fixes

### PR DESCRIPTION
**Pull request by vchong**

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by etienne-lms** [comment]
minor comment: in 1st commit, the comment state the issue is related to Andrdoid build env. Actually the issue is generic to any build env.

**Comment by vchong** [comment]
@etienne-lms I'll change it to `Fixes build error below:`, but don't know why the linux build is ok. The aosp toolchain I used is 4.9, so it's not really a gcc 5/6 issue.

**Comment by jenswi-linaro** [comment]
@vchong the warning can depend on which optimizations are used.

**Comment by vchong** [comment]
Rebased, commit messages updated and tag added. Ok to merge?

Thanks!

**Pull request merged**
