### PR TITLE
Simplify CMake library version declarations and configure include_directories for BUILD_INTERFACE and INSTALL_INTERFACE

### PR DESCRIPTION
**Pull request by eaaltonen**
Two CMake fix commits originally from the start of https://github.com/OP-TEE/optee_client/pull/259/ (stale).

* The version handling simplifies the CMake build a bit.
* BUILD_INTERFACE and INSTALL_INTERFACE are related to configuring paths differently for the build tree and install tree (_used if/when a CMake config-file package is added_).

These don't depend on `libuuid`, so can be brought in before those changes.

Refreshed with fixup commits for changes since last year.

### CODE REVIEW

**Comment by eaaltonen** [comment]
@etienne-lms: FYI I squashed the fixup (_refresh_) commits, but kept your `Reviewed-by` line.

**Comment by jforissier** [comment]
For commit "Remove setting include_directory for teec": do you mean `libseteec` rather than `teec`?

`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by eaaltonen** [comment]
> For commit "Remove setting include_directory for teec": do you mean `libseteec` rather than `teec`?

Re-phrased to
`Don't set teec include_directory from libseteec`
Hopefully that's more clear.

> `Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

And also added Acked-by.

**Comment by jforissier** [comment]
Would you mind adding a `cmake:` prefix to the last two commits? Thanks.

**Comment by eaaltonen** [comment]
> Would you mind adding a `cmake:` prefix to the last two commits? Thanks.

Not at all; and done. As long as you don't mind the slightly longer summary line.

**Pull request merged**
