### PR TITLE
Global Platform Internal Core API v1.1 update

### PR DESCRIPTION
**Pull request by cedric-chaumont-st-dev**
1st pass code update (no deprecated functions)

Change-Id: Ib1e17d4ea497bdb9bc3a4fa98067e889d2977696
Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by pascal-brand-st-dev** [comment]
I would change the commit message, as we may have several updates. Something like:

    GP Internal Core v1.1: Adding new defines

Apart from this

    Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jbech-linaro** [comment]
+1 with Pascal's comment.

**Comment by cedric-chaumont-st-dev** [comment]
Updated

**Comment by cedric-chaumont-st-dev** [comment]
Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (STM Cannes)
Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (FVP)

**Pull request merged**
