### PR TITLE
README: Update legacy toolchain download url

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
I checked all the other repos and think this and https://github.com/OP-TEE/optee_os/pull/1207 are the last ones for this issue. Hopefully I didn't miss anything and release team doesn't change file locations anymore.

**Comment by jenswi-linaro** [comment]
I think we're giving the url to the toolchain in too many places. Do we really need to have it anywhere except https://github.com/OP-TEE/build/blob/master/toolchain.mk ?

**Comment by vchong** [comment]
Yes, scripts are broken all over the place in other groups too. It is a pain. So replace the text with something general like `Download the appropriate toolchain from http://releases.linaro.org/components/toolchain/binaries/` and `/path/to/toolchain` in the instructions? Any other suggestions?

**Comment by jforissier** [comment]
@vchong sounds good.

**Comment by jbech-linaro** [comment]
@vchong instead of referring to `release.l.o`, what about instead referring to the the toolchains in `toolchain.mk` as suggested by Jens. By doing that, we know that we're referring to toolchains we have used and that we know are working in our setups?

**Comment by vchong** [comment]
Yes ok, good idea. Will make changes to refer to `toolchain.mk`.

**Comment by vchong** [comment]
Updated. Please see if new changes are ok. I'll also change commit title to `README: Replace toolchain URL with reference to toolchain.mk` when adding tags.

**Comment by jbech-linaro** [comment]
Yeps, that is great, thanks!
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by vchong** [comment]
You're welcome!
Commits squashed and tag added.

**Comment by jforissier** [comment]
Why did you split the subject line?

**Comment by vchong** [comment]
The vim editor follows the 50/72 rule and 'warns' me (by changing text color) after the 50 chars. Should I just ignore it and put everything on 1 line?

**Comment by jforissier** [comment]
50 characters? That's not much for a commit subject. `checkpatch.pl` warns for >75 if I'm not mistaken. Actually, I have run some stats on the Linux kernel. If you consider all commit subjects in the last 6 months (except merges), 42.04% are 50 characters or less, 54.33% are between 51 and 75 characters, and 3.63% are more than 76 characters. So, yes, please merge the first two lines ;)

**Comment by jbech-linaro** [comment]
Here is a nice image showing the distribution (peeks around 50 characters).
https://medium.com/@preslavrachev/what-s-with-the-50-72-rule-8a906f61f09c#.nm9p5nby4

**Comment by vchong** [comment]
Lines merged. Thanks!

**Comment by jforissier** [comment]
Yeah thanks for the link, nice graphical distribution. Personally, I don't approve the 50 rule, and it's good that checkpatch actually warns only for >75 (here: https://github.com/torvalds/linux/blob/master/scripts/checkpatch.pl#L2508). I'm OK with the 72 rule in the commit body, though (although by the same checkpatch standards we could do 75... not a big difference).

Anyway, thanks @vchong, patch merged.

**Pull request merged**
