### PR TITLE
libckteec: minor fixes

### PR DESCRIPTION
**Pull request by etienne-lms**

### CODE REVIEW

**Comment by Emantor** [comment]
`Acked-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>`

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
squashed. commit log not fixed.

**Comment by jforissier** [comment]
> commit log not fixed.
???
Why push without Jens' Ack?

**Comment by etienne-lms** [comment]
sorry, I was about to  and had to quit so I left this comment... so you don't merge...
I will update.

**Comment by etienne-lms** [comment]
updated

**Pull request merged**
