### PR TITLE
libckteec: Add elliptic curve support

### PR DESCRIPTION
**Pull request by vesajaaskelainen**
Add support for elliptic curve key pair generation, signing and verification operations.

Goes with:
- https://github.com/OP-TEE/optee_os/pull/4453
- https://github.com/OP-TEE/optee_test/pull/503

Relates to:
- https://github.com/OP-TEE/optee_os/issues/4283

### CODE REVIEW

**Comment by ruchi393** [comment]
The patches LGTM.

**Review by ricardosalveti — APPROVED** [review]
`Reviewed-by: Ricardo Salveti <ricardo@foundries.io>
`

**Comment by vesajaaskelainen** [comment]
> `Reviewed-by: Ricardo Salveti <ricardo@foundries.io> `

Thanks! Applied tags.

**Review by etienne-lms — APPROVED** [review]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`
sorry for the delay

**Comment by ruchi393** [comment]
`Reviewed-by: Ruchika Gupta<ruchika.gupta@linaro.org>`

**Comment by vesajaaskelainen** [comment]
> `Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`
> `Reviewed-by: Ruchika Gupta<ruchika.gupta@linaro.org>`

Thanks! Applied tags.

Minor note: modified commit message by removing ':' after mecha names.

**Pull request merged**
