### PR TITLE
tee_client_api: Fix typo in max shared memory size

### PR DESCRIPTION
**Pull request by LKostyra**
Resolves issue #88

### CODE REVIEW

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

Can you please also add your sign-off? Signed-off-by: tag, see https://github.com/OP-TEE/optee_os/blob/master/Notice.md#contributions and please provide a real name/email address as explained in the linux documentation: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst?h=v4.12-rc1#n424

**Comment by etienne-lms** [comment]
Actually this define is used nowhere. Isn't it a deprecated macro ?

**Comment by LKostyra** [comment]
All done. Sorry about that, missed the info about contribution.

**Comment by etienne-lms** [comment]
> Actually this define is used nowhere. Isn't it a deprecated macro ?

My mistake. This is specified by the GP TEE specs and there is a xtest over it.

**Comment by LKostyra** [comment]
@etienne-lms I've decided to check how Allocate/RegisterSharedMemory functions define this in the specification (4.5.4 and 4.5.5 - description of APIs TEEC_RegisterSharedMemory and TEEC_AllocateSharedMemory in TEE Client API specification):

>An Implementation MAY put a hard limit on the size of a single Shared Memory block, defined by the constant TEEC_CONFIG_SHAREDMEM_MAX_SIZE.

Basically, there's nothing wrong with the implementation on Client's side, as this check is not obligatory. That might explain why some xtests pass while surpassing this limit.

As for the value, it is stated in macro description in the same document (4.4.1):

> In systems where there is no limit imposed by the Implementation then this definition should be defined to be the size of the address space

If 31 MB mentioned by you is the limit for TAs in core implementation, then I guess this is the correct value.

**Comment by jforissier** [comment]
@etienne-lms you're probably right that 512 KB is not a good value, because it does not sound right that an allocation larger than `TEEC_CONFIG_SHAREDMEM_MAX_SIZE` can succeed.
Let's use 31 MB instead (where does this value come from? I think it would be nice to explain in a comment next to the #define)

**Comment by etienne-lms** [comment]
In current release, non-LPAE (resp. LPAE) offers 31MB (resp. 4GB) of va space to each TA.

The TA va space size can be retrieved at runtime through `core_mmu_get_user_va_range()`. I let you dig in the code to find how it's computed, it is not that complex but not that straightforward :)

**Comment by jforissier** [comment]
Thanks @etienne-lms. So, there's no unique good value, since it depends on the config, right?
So, should we do `#define TEEC_CONFIG_SHAREDMEM_MAX_SIZE ULONG_MAX`?

**Comment by jenswi-linaro** [comment]
Sounds good, especially with regards to the shared memory work @lorc is doing.

**Comment by LKostyra** [comment]
Corrected and modified the comment above the define.

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
Merged manually. Thanks!

**Pull request closed without merging**
