### PR TITLE
public: Fix simple typo in tee_client_api.h

### PR DESCRIPTION
**Pull request by miyatsu**
Replace TEEC_PARAMS_TYPE with TEEC_PARAM_TYPES.

Signed-off-by: Ding Tao <miyatsu@qq.com>

### CODE REVIEW

**Review by jforissier — APPROVED** [review]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

Thanks!

**Comment by miyatsu** [comment]
@jforissier Does github will automatic rebase to master branch? Or I have to rebase it my self locally and push again.

**Comment by jforissier** [comment]
@miyatsu no need to rebase, it will happen automatically. Please just add my Reviewed-by. Thanks!

**Comment by miyatsu** [comment]
@jforissier I rebased it any way. Ur `Reviewed-by` request also added, take a look pls.

**Pull request merged**
